Add "Getting Started - Software" guide
ebelski/rust-copter pull request #35
Opened 2021-01-26 01:06 UTC by mciantyre

- Add a written guide for first-time software installation
- Include a shell script to automate most of that first-time software
  installation (Linux / macOS only)
- Test that shell script

Looking for feedback on the docs quality, making sure that its easy
to read, and that it includes all of the dependencies and tools.

2021-01-26 01:28 UTC, mciantyre commented
Checks for `first-time-setup.sh` [passed in CI](https://github.com/ebelski/rust-copter/pull/35/checks?check_run_id=1766151570). I transitioned the test to a cron job, instead of running them on every PR / commit, since they run slower (need to download toolchains, build tools, build all code). Could use a dependency cache to avoid the crate download, but lets consider that if the cron job doesn't work out.

2021-01-26 01:33 UTC, mciantyre commented
Consider this getting started documentation for #23.

2021-01-27 14:22 UTC, ebelski requested changes
Under the "Install Rust" header, it says "...Visual Studio 2019. Read the relevant sections for more information". 
-> Are we pointing the user to somewhere in our documentation or the Rust programming documentation or the linker/build tools documentation? Would it be possible to say something like "...Read the relevant sections, in so and so docs, for more information"?

I plan on following these instructions for a clean install at some point, but so far I think you covered everything and in the right order

2021-01-28 00:06 UTC, mciantyre commented on docs/GettingStartedSoftware.md
> +information.
@ebelski I'll make it read something like

```suggestion
the Build Tools for Visual Studio 2019. Read the relevant sections of
[The Rust Programming Language] (Chapter 1) for more information.
```

2021-01-28 18:00 UTC, ebelski approved these changes
Thanks!

2021-01-28 18:01 UTC, merged